batch_size: 4
project_path: Full path of the working directory\Name of the project-Name of the experimenter-2022-10-12
iteration: 0
colormap: jet
alphavalue: 0.5
dotsize: 12
y2: 624
y1: 277
x2: 640
x1: 0
move2corner: true
corner2move2: !!python/tuple
- 50
- 50
pcutoff: 0.1
snapshotindex: -1
resnet: 50
TrainingFraction:
- 0.95
date: Oct12
scorer: Name of the experimenter
bodyparts:
- hand
- Finger1
- Finger2
- Joystick
numframes2pick: 20
stop: 1
start: 0
cropping: false
video_sets:
  E:\data2\Code\Luo_Alignment Project\VideoSlices.avi:
    crop: 0, 500, 0, 400
Task: Name of the project
